name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload files to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/centipede-driver.sys
            ./build/um.exe
            ./build/kdmapper_Release.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
